version: '3'

services:
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/node/app
      - /home/node/app/node_modules

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - 3001:3001
    volumes:
      - ./backend:/home/node/app
      - /home/node/app/node_modules

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mySecret1234
      MYSQL_DATABASE: users_db
    ports:
      - 3308:3306
    volumes:
      - ./database/setup/setup.sql:/docker-entrypoint-initdb.d/1.sql
      - ./database/data:/var/lib/mysql

# Links que me ajudaram a resolver o problema com a instalação das dependências
# https://mherman.org/blog/dockerizing-a-react-app/
# https://github.com/nodejs/docker-node/issues/740#issuecomment-538644464
